const stations = [
  {
    name: 'Milton',
    code: 'ML',
    miniScheduleFilename: 'Milton-Union.pdf',
    line: 'milton',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Lisgar',
    code: 'LS',
    miniScheduleFilename: 'Lisgar-Union.pdf',
    line: 'milton',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Kipling',
    code: 'KP',
    miniScheduleFilename: 'Kipling-Union.pdf',
    line: 'milton',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Dixie',
    code: 'DI',
    miniScheduleFilename: 'Dixie-Union.pdf',
    line: 'milton',
    rect: {},
    pages: {
      east: 2,
      west: 1,
    },
  },
  {
    name: 'Cooksville',
    code: 'CO',
    miniScheduleFilename: 'Cooksville-Union.pdf',
    line: 'milton',
    rect: {},
    pages: {
      east: 2,
      west: 1,
    },
  },
  {
    name: 'Erindale',
    code: 'ER',
    miniScheduleFilename: 'Erindale-Union.pdf',
    line: 'milton',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Streetsville',
    code: 'SR',
    miniScheduleFilename: 'Streetsville-Union.pdf',
    line: 'milton',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Meadowvale',
    code: 'ME',
    miniScheduleFilename: 'Meadowvale-Union.pdf',
    line: 'milton',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Exhibition',
    code: 'EX',
    miniScheduleFilename: 'Exhibition-Union.pdf',
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'Mimico',
    code: 'MI',
    miniScheduleFilename: 'Mimico-Union.pdf',
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'Long Branch',
    code: 'LO',
    miniScheduleFilename: 'LongBranch-Union.pdf',
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'Port Credit',
    code: 'PO',
    miniScheduleFilename: 'PortCredit-Union.pdf',
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'Clarkson',
    code: 'CL',
    miniScheduleFilename: 'Clarkson-Union.pdf',
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'Oakville',
    code: 'OA',
    miniScheduleFilename: 'Oakville-Union.pdf',
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'Bronte',
    code: 'BO',
    miniScheduleFilename: 'Bronte-Union.pdf',
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'Appleby',
    code: 'AP',
    miniScheduleFilename: 'Appleby-Union.pdf',
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'Burlington',
    code: 'BU',
    miniScheduleFilename: 'Burlington-Union.pdf',
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'Aldershot',
    code: 'AL',
    miniScheduleFilename: 'Aldershot-Union.pdf',
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'West Harbour',
    code: 'WR',
    miniScheduleFilename: 'WestHarbour-Union.pdf',
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'St Catharines',
    code: 'SCTH',
    miniScheduleFilename: null,
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'Niagara Falls',
    code: 'NI',
    miniScheduleFilename: 'NiagaraFalls-Union.pdf',
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'Hamilton',
    code: 'HA',
    miniScheduleFilename: 'Hamilton-Union.pdf',
    line: 'lakeshorewest',
    rect: {},
  },
  {
    name: 'Kitchener',
    code: 'KI',
    miniScheduleFilename: 'Kitchener-Union.pdf',
    line: 'kitchener',
    rect: {},
    pages: {
      east: 2,
      west: 1,
    },
  },
  {
    name: 'Pearson',
    code: 'PA',
    miniScheduleFilename: 'Pearson-Union.pdf',
    line: 'kitchener',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Guelph',
    code: 'GL',
    miniScheduleFilename: 'GuelphCentral-Union.pdf',
    line: 'kitchener',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Acton',
    code: 'AC',
    miniScheduleFilename: 'Acton-Union.pdf',
    line: 'kitchener',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Georgetown',
    code: 'GE',
    miniScheduleFilename: 'Georgetown-Union.pdf',
    line: 'kitchener',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Mount Pleasant',
    code: 'MO',
    miniScheduleFilename: 'MountPleasant-Union.pdf',
    line: 'kitchener',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Brampton',
    code: 'BR',
    miniScheduleFilename: 'Brampton-Union.pdf',
    line: 'kitchener',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Bramalea',
    code: 'BE',
    miniScheduleFilename: 'Bramalea-Union.pdf',
    line: 'kitchener',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Malton',
    code: 'MA',
    miniScheduleFilename: 'Malton-Union.pdf',
    line: 'kitchener',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Etobicoke North',
    code: 'ET',
    miniScheduleFilename: 'EtobicokeNorth-Union.pdf',
    line: 'kitchener',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Weston',
    code: 'WE',
    miniScheduleFilename: 'Weston-Union.pdf',
    line: 'kitchener',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Bloor',
    code: 'BL',
    miniScheduleFilename: 'Bloor-Union.pdf',
    line: 'kitchener',
    rect: {},
    pages: {
      east: 2,
      west: 2,
    },
  },
  {
    name: 'Centennial',
    code: 'CE',
    miniScheduleFilename: 'Centennial-Union.pdf',
    line: 'stouffville',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Markham',
    code: 'MR',
    miniScheduleFilename: 'Markham-Union.pdf',
    line: 'stouffville',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Mount Joy',
    code: 'MJ',
    miniScheduleFilename: 'MountJoy-Union.pdf',
    line: 'stouffville',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Stouffville',
    code: 'ST',
    miniScheduleFilename: 'Stouffville-Union.pdf',
    line: 'stouffville',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Lincolnville',
    code: 'LI',
    miniScheduleFilename: 'Lincolnville-Union.pdf',
    line: 'stouffville',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Agincourt',
    code: 'AG',
    miniScheduleFilename: 'Agincourt-Union.pdf',
    line: 'stouffville',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Milliken',
    code: 'MK',
    miniScheduleFilename: 'Milliken-Union.pdf',
    line: 'stouffville',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Unionville',
    code: 'UI',
    miniScheduleFilename: 'Unionville-Union.pdf',
    line: 'stouffville',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Kennedy',
    code: 'KE',
    miniScheduleFilename: 'Kennedy-Union.pdf',
    line: 'stouffville',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Richmond Hill',
    code: 'RI',
    miniScheduleFilename: 'RichmondHill-Union.pdf',
    line: 'richmondhill',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Langstaff',
    code: 'LA',
    miniScheduleFilename: 'Langstaff-Union.pdf',
    line: 'richmondhill',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Old Cummer',
    code: 'OL',
    miniScheduleFilename: 'OldCummer-Union.pdf',
    line: 'richmondhill',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Oriole',
    code: 'OR',
    miniScheduleFilename: 'Oriole-Union.pdf',
    line: 'richmondhill',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Gormley',
    code: 'GO',
    miniScheduleFilename: 'Gormley-Union.pdf',
    line: 'richmondhill',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Downsview Park',
    code: 'DO',
    miniScheduleFilename: 'DownsviewPark-Union.pdf',
    line: 'barrie',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'York University',
    code: 'YO',
    miniScheduleFilename: 'YorkUniversity-Union.pdf',
    line: 'barrie',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Rutherford',
    code: 'RU',
    miniScheduleFilename: 'Rutherford-Union.pdf',
    line: 'barrie',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Maple',
    code: 'MP',
    miniScheduleFilename: 'Maple-Union.pdf',
    line: 'barrie',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'King City',
    code: 'KC',
    miniScheduleFilename: 'KingCity-Union.pdf',
    line: 'barrie',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Aurora',
    code: 'AU',
    miniScheduleFilename: 'Aurora-Union.pdf',
    line: 'barrie',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Newmarket (Train Station)',
    code: 'NE',
    miniScheduleFilename: 'NewmarketGoTrainStation-Union.pdf',
    line: 'barrie',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Newmarket (Bus Terminal)',
    code: '00001',
    miniScheduleFilename: 'NewmarketBusTerminal-Union.pdf',
    line: 'barrie',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'East Gwillimbury',
    code: 'EA',
    miniScheduleFilename: 'EastGwillimbury-Union.pdf',
    line: 'barrie',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Bradford',
    code: 'BD',
    miniScheduleFilename: 'Bradford-Union.pdf',
    line: 'barrie',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Barrie South',
    code: 'BA',
    miniScheduleFilename: 'BarrieSouth-Union.pdf',
    line: 'barrie',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Allandale Waterfront',
    code: 'AD',
    miniScheduleFilename: 'AllandaleWaterfront-Union.pdf',
    line: 'barrie',
    rect: {},
    pages: {
      south: 2,
      north: 2,
    },
  },
  {
    name: 'Danforth',
    code: 'DA',
    miniScheduleFilename: 'Danforth-Union-Exhibition.pdf',
    line: 'lakeshoreeast',
    rect: {},
    pages: {
      east: 1,
      west: 2,
    },
  },
  {
    name: 'Scarborough',
    code: 'SC',
    miniScheduleFilename: 'Scarborough-Union-Exhibition.pdf',
    line: 'lakeshoreeast',
    rect: {},
    pages: {
      east: 1,
      west: 2,
    },
  },
  {
    name: 'Eglinton',
    code: 'EG',
    miniScheduleFilename: 'Eglinton-Union-Exhibition.pdf',
    line: 'lakeshoreeast',
    rect: {},
    pages: {
      east: 1,
      west: 2,
    },
  },
  {
    name: 'Guildwood',
    code: 'GU',
    miniScheduleFilename: 'Guildwood-Union-Exhibition.pdf',
    line: 'lakeshoreeast',
    rect: {},
    pages: {
      east: 1,
      west: 2,
    },
  },
  {
    name: 'Rouge Hill',
    code: 'RO',
    // typo in filename is deliberate to match GO transit typo...
    miniScheduleFilename: 'RogueHill-Union-Exhibition.pdf',
    line: 'lakeshoreeast',
    rect: {},
    pages: {
      east: 1,
      west: 2,
    },
  },
  {
    name: 'Pickering',
    code: 'PIN',
    miniScheduleFilename: 'Pickering-Union-Exhibition.pdf',
    line: 'lakeshoreeast',
    rect: {},
    pages: {
      east: 1,
      west: 2,
    },
  },
  {
    name: 'Ajax',
    code: 'AJ',
    miniScheduleFilename: 'Ajax-Union-Exhibition.pdf',
    line: 'lakeshoreeast',
    rect: {},
    pages: {
      east: 1,
      west: 2,
    },
  },
  {
    name: 'Whitby',
    code: 'WH',
    miniScheduleFilename: 'Whitby-Union-Exhibition.pdf',
    line: 'lakeshoreeast',
    rect: {},
    pages: {
      east: 1,
      west: 2,
    },
  },
  {
    name: 'Oshawa',
    code: 'OS',
    miniScheduleFilename: 'Oshawa-Union-Exhibition.pdf',
    line: 'lakeshoreeast',
    rect: {},
    pages: {
      east: 1,
      west: 2,
    },
  },
];

// Disable this export when running downloadpdfs script
export default stations;

export const stationsByName = stations.reduce((acc, curr) =>
  ({...acc, [curr.name.replace(/\s+/g, '').toLowerCase()]: curr}) ,{});

// Use this export for running the downloadpdfs script
// exports.stations = stations;
